# Generated by Django 3.2.8 on 2021-10-10 15:21

import advito.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='о себе'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование объявления')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='содержание объявления')),
                ('image', models.ImageField(upload_to=advito.models.user_directory_path, verbose_name='фотография товара')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('date_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата изменения')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='advito.category', verbose_name='категория товара')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='advito.post', verbose_name='объявления'),
        ),
    ]
